### ISSUE TITLE
The crosshair can't detect blocks well

### ISSUE THREAD

**Issue by ewoudje** [ValkyrienSkies/Valkyrien-Skies-2#116]
The crosshair can't detect blocks well when moving with highspeeds
Maybe we should use the rendertransform for this?

**Comment by Rubydesic** [comment]
Should already use it though: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/blob/849a9b7cf44e19e6cc578fc726b04a0a04cb734d/common/src/main/kotlin/org/valkyrienskies/mod/common/world/RaycastUtils.kt#L35-L36

**Comment by ZzStormKnightzZ** [comment]
When i was testing.  Being seated and uneven made trying to hit levers almost impossible. It was like the hit boxes moved from their blocks. this may be similar

**Comment by ewoudje** [comment]
> When i was testing. Being seated and uneven made trying to hit levers almost impossible. It was like the hit boxes moved from their blocks. this may be similar

Yes this was the problem i was seeing, mainly on high speeds. But im unsure if newer version still have this so ill test this soon after i get the new vs2 working in eureka.

**Comment by StewStrong** [comment]
I'm not able to replicate this issue anymore, I think we've fixed it over the past few months. Closing for now.

**Comment by copperwarrior** [comment]
This issue is still present at high speeds and odd angles.
https://i.gyazo.com/28a7226fbbfc77fe33650bac0530b861.mp4
