### ISSUE TITLE
does not load on quilt and fabric crashes on load

### ISSUE THREAD

**Issue by Zorro-no** [ValkyrienSkies/Valkyrien-Skies-2#419]
quilt ignores the mod and fabric crashes on load

**Comment by Rubydesic** [comment]
fixed in latest beta version of quilt

**Comment by Zorro-no** [comment]
no it didnt
![Screenshot (1)](https://user-images.githubusercontent.com/108409246/222924582-7d5722c6-c8a2-4592-ad07-69b5fccf308c.png)

**Comment by Zorro-no** [comment]
it didnt, still doesnt appear, with the latest version of beta quilt for 1.19.2

**Comment by TechTastic** [comment]
We are not on 1.19.2 yet, unless you are a playtester and built the 1.19.2 version yourself
