### ISSUE TITLE
Weird physics breakage: IMPORTANT

### ISSUE THREAD

**Issue by VosmoslaGod** [ValkyrienSkies/Valkyrien-Skies-2#464]
https://cdn.discordapp.com/attachments/1102598426320965652/1102629882208456758/javaw_5AT9FJLyxU.mp4 
https://cdn.discordapp.com/attachments/1102598426320965652/1102598426857840671/javaw_yzd4mmA48t.mp4
https://cdn.discordapp.com/attachments/1102598426320965652/1102609815466950726/javaw_oizhPBbL7A.mp4

I just used Discord to send these video files as they are too big for GitHub. The issue is pretty self explanatory.

the mod list below: Forge 40.2.1 for Minecraft 1.18.2
![image](https://user-images.githubusercontent.com/94943333/235487401-bf38cab9-3852-4fe3-856d-323f969782c1.png)

**Comment by VosmoslaGod** [comment]
Side note I tried with only vs2 and it still persists

**Comment by Oldtvstudio** [comment]
(translator warn srry)Something similar happens to me with the hitboxes but in my case they don't match the blocks and they get so big that they go through the ground. Most likely it's a bug when trying to implement what is necessary to be able to use VS:Clockwork and there caused failures in the hitboxes

**Comment by StewStrong** [comment]
This should be fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/pull/475

**Comment by VosmoslaGod** [comment]
Infact not fixed, open this back up. YOu did not fix the issue. I used the latest dev package
