### ISSUE TITLE
1.20.1 high memory leak report

### ISSUE THREAD

**Issue by lostopkk** [ValkyrienSkies/Valkyrien-Skies-2#525]
This report will be strange because I couldn't record the video with Valkyrie Skies running because of the high memory consumption and my computer can't handle it.
I've been testing my modpack when it's without Valkyrie Skies it's between 2900-3100 mb which is a considerable measure since I allocated 2 gb ram. But when I put the valkyrie skies not only increases to 3600-3800, but also every time I render a chunk the memory increases hitting up to 4200 mb!
I have a log of him hitting this and my computer can't handle it.

NO valkyrien skies 2: https://drive.google.com/file/d/1hLvp8OhOHkwFREb6BboaK1AEKDiYc7rI/view?usp=sharing
With valkyrien skies 2: [2023-07-06-1.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11974161/2023-07-06-1.log)

another problem is the log spam in case the game is stopped doing nothing the valkyrien skies starts to print madly.
log: [2023-07-05-6.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11974167/2023-07-05-6.log)

**Comment by Shurelia** [comment]
can confirm this, ive made a support thread with this exact same question before
https://canary.discord.com/channels/244934352092397568/1126686246706622545/1126686246706622545

**Comment by austin-meadows** [comment]
Would like to bump this, two seperate hosts (bloom.host / cloudnord.net) I've hosted this mod with, and in both cases the memory eventually maxes out and the server crashes.

**Comment by catsz** [comment]
I can comfirm on my linux 1.18.2 server valk uses all the memory until it crashes.

**Comment by Ragazzone13** [comment]
I can also confirm, my 6gb server which should be plenty for a lightly modded server (my case only having VS and some other smaller mods) crashes.

**Comment by Neubulae** [comment]
can confirm

**Comment by luigistyle** [comment]
Can confirm, server runs completely fine with 6GB allocated but loading enough chunks with this mod (and Eureka) has sometimes caused memory usage to go up to ~17GB and crash the server due to running out of memory.

**Comment by Baobab3001** [comment]
I can confirm, even when you are not driving boats, the ram usage goes up quickly for no reason until it crashes.
it is a good mod, maybe one of the best among all the mods, but its poorly optimized (I know it's still in beta, but this bug has persisted for a long time).
no matter how much ram is allocated to the server, this mod will take it all away making it unplayable.
too unstable to recommend in any modpack.

**Comment by simon511000** [comment]
I can confirm too

**Comment by Novasky-Guy** [comment]
Can confirm this is happening here too. New chunks seem to increase the ram until it fully crashes the server.

**Comment by StewStrong** [comment]
This is fixed in the latest 1.18.2 versions, however 1.19.2 and 1.20.1 haven't had their krunch updated yet, so its still an issue there. We will post new builds of 1.19 and 1.20 to curse soon.

**Comment by Faolon12** [comment]
has it been updated yet? runing on a server, and without the mod, usage is about 6gb, with the mod, i end up using 82gb after 4 hours of exploring in a airship,

**Comment by PriestOfFerns** [comment]
> has it been updated yet? runing on a server, and without the mod, usage is about 6gb, with the mod, i end up using 82gb after 4 hours of exploring in a airship,

1.20 and 1.19 somewhat recently got updated to be on track with 1.18. So it should have been fixed

**Comment by CorneliusCornbread** [comment]
> > has it been updated yet? runing on a server, and without the mod, usage is about 6gb, with the mod, i end up using 82gb after 4 hours of exploring in a airship,
> 
> 1.20 and 1.19 somewhat recently got updated to be on track with 1.18. So it should have been fixed

Can confirm this has not been fixed, our server has been leaking memory, reaching usages of 16GB or more and often crashing because of it

**Comment by Baobab3001** [comment]
The problem persists, even with the presence of only one boat in the server, it becomes slower and slower until it closes.
Once the mod is removed, the server that uses all 16 RAM will use a quarter of them.
I'd say it's still quite expensive, and still unplayable.
I repeat, fantastic mod, but not yet enjoyable.
(game in 1.18 on a modded server, the problem exists with or without additional mods)

**Comment by PriestOfFerns** [comment]
> The problem persists, even with the presence of only one boat in the server, it becomes slower and slower until it closes.
> Once the mod is removed, the server that uses all 16 RAM will use a quarter of them.
> I'd say it's still quite expensive, and still unplayable.
> I repeat, fantastic mod, but not yet enjoyable.
> (game in 1.18 on a modded server, the problem exists with or without additional mods)

are you sure updated VS2. I’ve ran this mod on my own fairly small 8 GB RAM server without issues and I’ve even seen people run VS2 on some free server hosts. And some of that was before this update even happened

**Comment by boniblade** [comment]
This is still going for VS2 as of 5/28/2024 on my 1.20.1 Forge server. Please hurry.

**Comment by zebogan** [comment]
this issue still exists with v2.1.1-beta.5 for 1.18.2

**Comment by Thunderstrike597** [comment]
I can confirm for the latest version of Valkyrien Skies on 1.19.2, the memory leak still exists. However, I have got more info that could be helpful. 
--------------
----------
So, for the past week ive been on several test worlds so I could build a ship for my main world in hopes the memory leak would be small when I build it in my world. So, I finish the ship and am ready to go to my main world which has Never had Any ship in it. 15- 25 minutes into gameplay (Still haven't built the ship, just gathering materials), the game freezes, un-freezes, then freezes again. Yeah I checked f3 and the ram has bumped up from 30%-40% to 98%-100%.
--------
[Long story short + more info]
My main world which has never had any ship/vehicle in it, is getting memory leak. So this leads me to believe either 1.The ships/vehicle data using up memory causing the leak carrying over between worlds, or 2. The leak might not be caused by the vehicles/ships at ALL(I think this could be true, but I don't know the workings of the mod, so who knows I'm probably wrong about both)
--------
also, it's worth mentioning that from what the comment above said (about chunk loading speeding up the memory leak) So from my testing, while it does MASSIVELY speed it up, I don't think it's the cause because since I have been running my own tests, it still leaks memory while inside my base (presuming I'm in my base moving and not on the pause screen). I could be wrong about the chunk loading not the direct cause and am just mistaken, but I don't think I am.

So yeah, I hope this helps in any way possible. Your mod is amazing but its almost unplayable. Sorry if this post was too much or too formal, just wanted to give you guys a bit more info that could help getting this massive bug fixed. GL

**Comment by PriestOfFerns** [comment]
@zebogan 1.18 is very much so memory leak free, while 1.19 and 1.20 are generally buggy and unstable, 1.18 is free from any major memory leak issues. Me and many other people ran perfectly stable servers for 1.18. Whatever you're experiencing is either not an issue with vanilla VS2, or is not in anyway related to this post

**Comment by Robert-Proaps** [comment]
Can confirm on 1.10.1

**Comment by blackvccat** [comment]
When I am driving a ship, running the single-player archive through cc is normal, but it will cause the server's memory to overflow. The server operates on the kvm architecture, and the memory is allocated to 64g, but when running the ship, the jvm applies to the host. 2tb of memory requirements, which is incredible, and there are also related questions about Too many physics frames in the physics frame queue. Is the game stage broken?                                                                                                                                           #933

**Comment by EliasRipley** [comment]
Following this thread as Valk Skies loops with Physics Queue error then crashes server. Forge 1.20.1. Working perfectly in single player.

**Comment by EliasRipley** [comment]
To my understanding, the reason this mod works in single player yet not on popular server hosts is because it requires 'pid' value to be 0 or -1.
Host owners have told me they are unwilling to make this change as it could be a security concern.

**Comment by SongOfCarp** [comment]
### This issue still occurs under 1.20.1 v2.3.0-beta.5 forge47.3.11. 
Someone said change setting "_synchronizePhysics_" to false will fix this, but it just stops server show "_Too many physics frames in the physics frame queue. Is the game stage broken?_", **the issue still exsists.** 
And I can confirm that this problem must related to chunk load or time. After the sever start, most of the main threads are dealing with this, which makes the server's TPS under 0.1, but server is runing, and I can see the java takes 1G more than I set. Then after a while(maybe the work is done?), the TPS comes up. It takes much much longer when I load a larger save.
-----------------------------
_I don't know if I said clear above, I'll explain below. As I start my server with a new world, the tps is only about 5 at very first. After about 1 minute, the tps backs to 20, and everything goes okay. But if I start server with a save about 10GB, it takes a couple of minute to reach 5TPS, **and it stabled around 5!**(by the way, the tps at very first is under 0.1, the server takes more than 10 seconds to respond my command) And after about 5 hours, the server crashed with "java.lang.OutOfMemoryError: Java heap space"._
------------------------------
I guess the fix mentioned in this issue before just controlled the memory leak outside the JVM, but it somehow happens slowly inside JVM, which caused the low TPS and out of memory.

**Comment by LilTwinky** [comment]
Any update on this issue getting fixed?

**Comment by blackvccat** [comment]
> Any update on this issue getting fixed?

NO

**Comment by nullsoepic** [comment]
Since this seems to still be a problem I thought I'd share my jank solution.
After trying to debug it for a while I noticed that pterodactyl and spark report different memory usage (since ptero reports container memory usage, and spark JVM memory usage). Spark also showed that large portion of cpu utilization came down to glibc. After reading a lot about this in the discord, I found out that the physics engine that vs runs on is separate from the mod and written in c++, which would explain the issues, like the garbage collector not impacting the memory leak at all because it was caused by a process separate from the JVM. Unfortunately unlike the actual valkyrien skies mod, the physics engine is not open source (and apparently will not be opensourced).

As a "might as well give it a shot" thing I decided to try and "frankenstein" the mod, jar files are just fancy zip files, so I copied the libKrunchJni64.so from the 1.18 version of the mod to the 1.20 one, which surprisingly worked, server has been running smoothly for ~4 days now with memory usage not going up at idle and eventually settling at the same spot when no players are online, which compared to how long it lasted before (less than a day) seems like a success to me.

You'd copy a different file based on which platform you're on:
libKrunchJni64.so for linux
libKrunchJniarm64.so for linux on arm
KrunchJni64.dll for windows
libKrunchJni64.dylib for macos
(or just move them all, doesn't hurt)

It is scuffed but it worked for me and I haven't noticed any issues so far. IIRC someone in the discord mentioned that this has been fixed in the latest dev versions of the mod but also that those aren't supported by most addons.

**Comment by LilTwinky** [comment]
Shot you a message on telegram

**Comment by thetheaplant** [comment]
> Since this seems to still be a problem I thought I'd share my jank solution. After trying to debug it for a while I noticed that pterodactyl and spark report different memory usage (since ptero reports container memory usage, and spark JVM memory usage). Spark also showed that large portion of cpu utilization came down to glibc. After reading a lot about this in the discord, I found out that the physics engine that vs runs on is separate from the mod and written in c++, which would explain the issues, like the garbage collector not impacting the memory leak at all because it was caused by a process separate from the JVM. Unfortunately unlike the actual valkyrien skies mod, the physics engine is not open source (and apparently will not be opensourced).
> 
> As a "might as well give it a shot" thing I decided to try and "frankenstein" the mod, jar files are just fancy zip files, so I copied the libKrunchJni64.so from the 1.18 version of the mod to the 1.20 one, which surprisingly worked, server has been running smoothly for ~4 days now with memory usage not going up at idle and eventually settling at the same spot when no players are online, which compared to how long it lasted before (less than a day) seems like a success to me.
> 
> You'd copy a different file based on which platform you're on: libKrunchJni64.so for linux libKrunchJniarm64.so for linux on arm KrunchJni64.dll for windows libKrunchJni64.dylib for macos (or just move them all, doesn't hurt)
> 
> It is scuffed but it worked for me and I haven't noticed any issues so far. IIRC someone in the discord mentioned that this has been fixed in the latest dev versions of the mod but also that those aren't supported by most addons.
> 
> [A more specific guide](https://gist.github.com/nullsoepic/88772ba16d3de9d93067d504c9ae3fdb)

Somehow this is a legitimate solution, well done. @nullsoepic

**Comment by PriestOfFerns** [comment]
@nullsoepic all of the files you mentioned are identical between the modrinth latest 1.18 and 1.20 vs2.

**Comment by nullsoepic** [comment]
Looks like I made a mistake. Couldn't replicate the issue on a test server with just VS, so probably something else was going on in my case. Sorry for jumping the gun and claiming a solution without double-checking. I've deleted my original comment to avoid spreading confusion

**Comment by Carro1001** [comment]
Any updates on this issue? I've read that the dev team is currently rewriting the mod, so I'm curious on what can be done for the time being, if anything

**Comment by Thunderstrike597** [comment]
> @Carro1001 no one seems to be able to consistently replicate it. It's blamed on a bunch of completely random and most likely unrelated mods and most people's fixes for it don't actually do anything.
> 
> So there's basically nothing you can do, other than swap to 1.18, where the issue may or may not exist

I'm wondering if it could be due to clockwork, because in my playthrough 1.20.1, it is mostly rare for it to happen without clockwork(It might occur every now and then, but for the most part, no). But as soon as I add clockwork it decides to happen within 20 minutes often enough. So I've had to remove clockwork (Which is sad, because it's soo cool).

I notice, clockwork hasn't been updated in a while, is it still in development?

**Comment by Clawmark27** [comment]
Did removing clockwork solve the issue? I've been working to solve it a while. Not sure why, but switching from GAUSS_SIEDEL to JACOBI appears to make the error take longer to trigger. Also, @EliasRipley mentioned something to do with PID value. I don't know anything about that so I'm wondering what it would affect. I think I could get that changed so if you could explain what that does that would be helpful.

**Comment by Wolfixsp** [comment]
From what i've tested the DPID and JACOBI fixes just delay the problem, memory leak issue gets worse when loading chunks with stuff like chunky, just after about 10 minutes the server will crash when pregenerating, only happens when VS is present, even if the only mods installed are chunky with VS and dependencies

**Comment by Ethonodon** [comment]
> [@Carro1001](https://github.com/Carro1001) no one seems to be able to consistently replicate it. It's blamed on a bunch of completely random and most likely unrelated mods and most people's fixes for it don't actually do anything.
> 
> So there's basically nothing you can do, other than swap to 1.18, where the issue may or may not exist

I can confirm the issue definitely exists in 1.18.2. Been having this problem for a while and have been so frustrated by it because no one seems to have any idea how to fix it.

**Comment by PriestOfFerns** [comment]
@Ethonodon Are you sure it happens on 1.18? I’ve run an enormous amount of servers on 1.18.2 and have yet to experience any memory issues

**Comment by Ethonodon** [comment]
> [@Ethonodon](https://github.com/Ethonodon) Are you sure it happens on 1.18? I’ve run an enormous amount of servers on 1.18.2 and have yet to experience any memory issues

As close to positive as I can be. Whenever I load chunks (even pre generated ones, btw) while VS is active, RAM usage skyrockets and stays there until the server crashes. I had this issue in 1.19.2 as well, but didn't think it was present in 1.18.2 too. I guess it could _maybe_ be an add-on? I'm using Clockwork and Eureka, but I also had those on my past 1.19.2 server where I experienced the same memory leak so I think it's reasonable to assume it's the same issue

**Comment by Ethonodon** [comment]
@PriestOfFerns had a thought, what specific version of VS are you using for 1.18.2? Mine is 2.1.1

**Comment by Robert-Proaps** [comment]
Just wondering now that time has passed, are people having this issue exclusively on server games, or does it exist in singleplayer as well?

**Comment by Ethonodon** [comment]
> Just wondering now that time has passed, are people having this issue exclusively on server games, or does it exist in singleplayer as well?

personally I've only experienced it with servers

**Comment by xunto** [comment]
Had server crash on 1.19.2, but I think it happened on 1.12.2 too. So basically it always leaked.

**Comment by Clawmark27** [comment]
Was this ever fixed?

**Comment by catsz** [comment]
> Was this ever fixed?

It does not appear to be fixed. You could test by running it on a server for a bit

**Comment by blockninja124** [comment]
This is believed to be fixed, in 1.20.1 at least, after we fixed a bug (fix was released in beta.6) that caused exponentially more RAM usage the more entities you loaded. Any other reports of “memory leak” that weren’t fixed by that haven’t been replicable. (And are usually reported on huge modpacks…)

**Comment by catsz** [comment]
oh I see. Why is the issue not closed then?

**Comment by blockninja124** [comment]
Because the GitHub is a little disorganised at the moment, and we also can’t be sure someone won’t add on to this discussion with an actual replicable new memory leak.

**Comment by Camawama** [comment]
I have been trying to figure out why server performance has been terrible on my modpack. I have 8GB RAM allocated but after the server runs for a few hours, RAM usage is at 21GB AND CLIMBING!! Does not appear to happen when VS is removed. This is pain.

**Comment by blockninja124** [comment]
@Camawama What version is your valkyrien skies, and can you send a latest.log?

**Comment by Rikipalooza** [comment]
Also on 1.20.1. Friends run a server with over 130 mods. We tried adding Valkyrien Skies and Eureka and server started crashing, RAM ramps up like crazy even before anyone joins the server. We spent a lot of hours replacing mods to diagnose it, and were left with these two. Removing them fixes it, adding them breaks it.

**Comment by thetheaplant** [comment]
@Rikipalooza can we get a latest.log and a spark profile?

**Comment by Rikipalooza** [comment]
Sorry the server was busy today but I did ask for the files.
Apparently the server doesn't crash, but the players do. And the RAM still goes way above what's permitted by the host.

[latest.log](https://github.com/user-attachments/files/22324896/latest.log)

[Qp8tXXGKck.zip](https://github.com/user-attachments/files/22324902/Qp8tXXGKck.zip)

**Comment by thetheaplant** [comment]
@Rikipalooza could we get a client crashlog then, and perhaps a spark profile?

**Comment by blockninja124** [comment]
That doesn't sound like an actual memory leak. That sounds like VS has managed to use more RAM than the host allocates because it uses RAM outside of MC to keep the physics performant, with another issue on top of that of clients crashing occasionally.

**Comment by Rikipalooza** [comment]
If it's a memory leak or not I can't say, all I can say is adding those two more than doubles the RAM used at startup, and if permitted, it keeps growing.
For most players it's not an actual crash, it's them being kicked out of the server, and the server stops answering for 2 minutes. Then it comes back. It happened once on those logs that I shared. Sorry for not correctly expressing what happens.

**Comment by thetheaplant** [comment]
@Rikipalooza Alright, so can we please get a profile and a client crashlog, so we can try to diagnose the specific issue

**Comment by Rikipalooza** [comment]
While talking to them, those who hard crash seem to be using Embeddium which is afaik not compatible with valkyrien so that would explain them correct?

But the server kicking out everyone and being unresponsive while the RAM ramps up, doesn't create a player crashlog afaik

**Comment by thetheaplant** [comment]
Embeddium shouldn't cause a crash in game, and afaik all modern embeddium versions are compatible.

**Comment by Rikipalooza** [comment]
[crash-2025-09-14_23.32.56-client.txt](https://github.com/user-attachments/files/22325955/crash-2025-09-14_23.32.56-client.txt)

**Comment by blockninja124** [comment]
That crash is caused by litematica, which isn't compatible with VS (it crashes sometimes)

**Comment by Rikipalooza** [comment]
And on the spark profile and latest log of the server everything seems fine?

**Comment by blockninja124** [comment]
Yes. Your spark profiler looks totally normal, and your logs have no visible errors.

**Comment by filtemprosa-oss** [comment]
have this problem in 1.20.1 on a shockbyte server, still occurs even with no ships around. main addons i have are clockwork and trackwork

**Comment by blockninja124** [comment]
@filtemprosa-oss No one has managed to reproduce an actual memory leak since VS beta.6, aside from pterodactyl sometimes restricting VS in weird ways. So we can't do much with your report unless you can provide some more evidence. Perhaps you could provide a latest.log, spark profile, and a modlist?

**Comment by blockninja124** [comment]
Closing this issue as it causes confusion.
