### ISSUE TITLE
Create 0.5.1-f-build.1417 and Create Interactive

### ISSUE THREAD

**Issue by Mapter228** [ValkyrienSkies/Valkyrien-Skies-2#813]
### Mod Name

Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Create interactive does not work together with the latest version of Create on fabric

### Issue reproduction

Crashes when loading the world

**Comment by thetheaplant** [comment]
Please add logs for your issue.

**Comment by Mapter228** [comment]
`WARNING: Using incubator modules: jdk.incubator.vector
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[10:14:02] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.9
[10:14:02] [main/WARN]: Mod resolution failed
[10:14:02] [main/INFO]: Immediate reason: [NEG_HARD_DEP create 0.5.1-f-build.1417+mc1.20.1 {breaks create_interactive @ [<=1.0.2-beta.1]}, ROOT_FORCELOAD_SINGLE create 0.5.1-f-build.1417+mc1.20.1, ROOT_FORCELOAD_SINGLE create_interactive 1.0.2-beta.1]
[10:14:02] [main/INFO]: Reason: [NEG_HARD_DEP create 0.5.1-f-build.1417+mc1.20.1 {breaks create_interactive @ [<=1.0.2-beta.1]}]
[10:14:02] [main/INFO]: SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, fabric-keybindings-v0, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, flywheel, fabric-models-v0, fabric-rendering-v0, fabric-sound-api-v1, fabric-key-binding-api-v1, fabric-rendering-v1]
[10:14:02] [main/INFO]: Fix: add [], remove [], replace [[create 0.5.1-f-build.1417+mc1.20.1] -> add:create 0.5.1-d-build.1161+mc1.20.1 ([[0.5.1-d-build.1161+mc1.20.1,∞)])]
[10:14:02] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
- Replace mod 'Create' (create) 0.5.1-f-build.1417+mc1.20.1 with version 0.5.1-d-build.1161+mc1.20.1 or later that is compatible with:
- create_interactive 1.0.2-beta.1
More details:
- Mod 'Create' (create) 0.5.1-f-build.1417+mc1.20.1 is incompatible with version 1.0.2-beta.1 or earlier of mod 'Create: Interactive' (create_interactive), but a matching version is present: 1.0.2-beta.1!
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.9.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.9.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.9.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.9-launcher.1.0.0.jar:1.0.0]
`

**Comment by mrsterner** [comment]
This is fixed in-dev, wait for next release

**Comment by Mapter228** [comment]
I noticed they released a new version, but still the same error

**Comment by thetheaplant** [comment]
Interactive, not vs issue.
